name: Axe
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  axe:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 18.x
        uses: actions/setup-node@v1
        with:
          node-version: 18.x
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - run: yarn start & npx wait-on http://localhost:8000
      - name: Run axe
        run: |
          yarn global add @axe-core/cli
          axe http://localhost:8000  --browser firefox --exit
