name: Continuous Integration

on: [pull_request]

jobs:
  buildLintTest:
    name: Build, Lint, and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install pnpm
        run: npm install -g pnpm
      - name: Install Dependencies
        run: pnpm i
      - name: Build
        run: pnpm build
      - name: Lint
        run: pnpm lint
      - name: Test
        run: pnpm test --watchAll=false
